<?php

namespace TrainingKeval\FeedBack\Ui\Component\Listing\Column;

use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class FeedBackActions extends Column
{
    protected $url;
    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        UrlInterface $url,
        array $components = [],
        array $data = []
    ) {
        parent::__construct($context, $uiComponentFactory, $components, $data);
        $this->url = $url;
    }

    /**
     * @param array $dataSource
     * @return array
     */
    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as &$item) {
                $item[$this->getData('name')]["view"]=
                    ['href'=>$this->url->getUrl('feedback/customer/view', ['id' => $item['entity_id']])
                        ,'label'=>__('View'),'hidden'=>false];
                $item[$this->getData('name')]["edit"]=
                    ['href'=>$this->url->getUrl('feedback/customer/edit', ['id' => $item['entity_id']])
                        ,'label'=>__('Edit'),'hidden'=>false];
                $item[$this->getData('name')]["delete"]=
                    ['href'=>$this->url->getUrl('feedback/customer/delete', ['id' => $item['entity_id']])
                        ,'label'=>__('Delete'),'hidden'=>false];
            }
        }
        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }
}
