<?php


namespace TrainingKeval\AdminLoginLog\Ui\Component\Listing\Column;


use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class Status extends Column
{
    public function __construct(ContextInterface $context, UiComponentFactory $uiComponentFactory, array $components = [], array $data = [])
    {
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }
    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as &$item) {
                if ($item['status'] == 1) {
                    $item['status'] = 'logged in';
                } elseif ($item['status'] == 2) {
                    $item['status'] = 'logged out by another login with the same credentials';
                } elseif ($item['status'] == 3) {
                    $item['status'] = 'logged out manually from another session';
                } else {
                    $item['status'] = 'logged out';
                }
            }
        }
        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }
}