<?php


namespace TrainingKeval\FeedBack\Model\ResourceModel\FeedBack;


use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use TrainingKeval\FeedBack\Model\ResourceModel\FeedBack as FeedbackResource;
use TrainingKeval\FeedBack\Model\FeedBack;

class Collection extends AbstractCollection
{
    protected $_idFieldName = 'entity_id';

    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init(FeedBack::CLASS, FeedbackResource::class);
    }
}