<h1>FeedBack Form</h1>
<form class="form" id="feedback-form" method="post" action="<?php echo $block->getBaseUrl()?>feedback/index/save" data-mage-init='{"validation":{}}'>
    <div class="form-group">
        <label class="control-label col-sm-2" for="first_name">First Name:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="first_name" placeholder="First Name" name="first_name" data-validate='{"required": true}'>
        </div>
    </div>
    <br/>
    <div class="form-group">
        <label class="control-label col-sm-2" for="last_name">Last Name:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="last_name" placeholder="Last Name" name="last_name" data-validate='{"required": true}'>
        </div>
    </div>
    <br/>
    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email:</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="email" placeholder="Email" name="email" data-validate='{"required": true, "validate-email":true}'>
        </div>
    </div>
    <br/>
    <div class="form-group">
        <label class="control-label col-sm-2" for="rating">Rating:</label>
        <div class="field required review-field-ratings">
            <div class="control review-control-vote" style="width:50%">
                <input type="radio" name="rating" id="Rating_1" value="1"  data-validate="{'validate-one-required-by-name':true}" class="radio" aria-labelledby="Rating_rating_label Rating_1_label" aria-required="true">
                <label class="rating-1" for="Rating_1" title="1 star" id="Rating_1_label">
                    <span>1 star</span>
                </label>
                <input type="radio" name="rating" id="Rating_2" value="2"  data-validate="{'validate-one-required-by-name':true}" class="radio" aria-labelledby="Rating_rating_label Rating_2_label" aria-required="true">
                <label class="rating-2" for="Rating_2" title="2 stars" id="Rating_2_label">
                    <span>2 stars</span>
                </label>
                <input type="radio" name="rating" id="Rating_3" value="3" data-validate="{'validate-one-required-by-name':true}" class="radio" aria-labelledby="Rating_rating_label Rating_3_label" aria-required="true">
                <label class="rating-3" for="Rating_3" title="3 stars" id="Rating_3_label">
                    <span>3 stars</span>
                </label>
                <input type="radio" name="rating" id="Rating_4" value="4" data-validate="{'validate-one-required-by-name':true}" class="radio" aria-labelledby="Rating_rating_label Rating_4_label" aria-required="true">
                <label class="rating-4" for="Rating_4" title="4 stars" id="Rating_4_label">
                    <span>4 stars</span>
                </label>
                <input type="radio" name="rating" id="Rating_5" value="5" data-validate="{'validate-one-required-by-name':true}" class="radio" aria-labelledby="Rating_rating_label Rating_5_label" aria-required="true">
                <label class="rating-5" for="Rating_5" title="5 stars" id="Rating_5_label">
                    <span>5 stars</span>
                </label>
            </div>
        </div>
    </div>
    <br/><br/>
    <div class="form-group">
        <label class="control-label col-sm-2" for="message">Message:</label>
        <div class="col-sm-10">
            <textarea class="form-control" id="message" placeholder="Message" name="message" data-validate='{"required": true}'></textarea>
        </div>
    </div>
    <br/>
    <div class="form-group">
        <div class="g-recaptcha" name="recaptcha" id="recaptcha" data-sitekey="6LeMp8sUAAAAALt7DEdC5RSX9UMUvIpOQMeCOwhb"></div>
    </div>
    <br/>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" name="feedback_submit" id="feedback_submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>